export const reportTabs = [
  {
    key: 'valuation',
    label: 'Valuation',
    metricLabel: 'Inventory Value',
    metricValue: '$482.4K',
    chartType: 'bar',
    summary: [
      { label: 'Finished Goods', value: '$214K' },
      { label: 'Raw Materials', value: '$173K' },
      { label: 'Packaging', value: '$95K' },
    ],
    data: [
      { name: 'A', value: 214 },
      { name: 'B', value: 173 },
      { name: 'C', value: 95 },
    ],
  },
  {
    key: 'turnover',
    label: 'Turnover',
    metricLabel: 'Annual Turns',
    metricValue: '5.8x',
    chartType: 'line',
    summary: [
      { label: 'Fast Movers', value: '38%' },
      { label: 'Mid Movers', value: '44%' },
      { label: 'Slow Movers', value: '18%' },
    ],
    data: [
      { name: 'Jan', value: 4.8 },
      { name: 'Feb', value: 5.1 },
      { name: 'Mar', value: 5.4 },
      { name: 'Apr', value: 5.5 },
      { name: 'May', value: 5.8 },
    ],
  },
  {
    key: 'slow-moving',
    label: 'Slow-Moving',
    metricLabel: 'Dormant SKUs',
    metricValue: '46',
    chartType: 'bar',
    summary: [
      { label: '60+ Days', value: '19' },
      { label: '90+ Days', value: '14' },
      { label: '120+ Days', value: '13' },
    ],
    data: [
      { name: '60d', value: 19 },
      { name: '90d', value: 14 },
      { name: '120d', value: 13 },
    ],
  },
  {
    key: 'aging',
    label: 'Aging',
    metricLabel: 'Average Age',
    metricValue: '74 days',
    chartType: 'line',
    summary: [
      { label: 'Fresh', value: '42%' },
      { label: 'Mid-Life', value: '36%' },
      { label: 'Aged', value: '22%' },
    ],
    data: [
      { name: 'Q1', value: 69 },
      { name: 'Q2', value: 72 },
      { name: 'Q3', value: 74 },
      { name: 'Q4', value: 76 },
    ],
  },
  {
    key: 'forecasting',
    label: 'Forecasting',
    metricLabel: 'Projected Fill Rate',
    metricValue: '96.4%',
    chartType: 'line',
    summary: [
      { label: 'Projected Demand', value: '1,920' },
      { label: 'Planned Receipts', value: '1,840' },
      { label: 'Risk SKUs', value: '11' },
    ],
    data: [
      { name: 'W1', value: 93.2 },
      { name: 'W2', value: 94.6 },
      { name: 'W3', value: 95.7 },
      { name: 'W4', value: 96.4 },
    ],
  },
];
